### PR TITLE
Add syntax support for map

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR adds syntax support for map.

According to the discussion of Issue #75, the map syntax now is

```clojure
%{:key1 :value1
  :key2 :value2}
```
the keys and values of A map is written between ```%{``` ```}```.

The choice of char % as prefix identifier char for map is borrowed from Elixir, which differs the map syntax ```#{ key => value }``` in Erlang a little bit in order to notify programmers that In Joxa a map is somewhat different since its keys and values must be in pair and matched by their positions(so no arrow ```=>``` between keys and values, although Elixir still keeps them in order to look like Ruby). Without ```=>``` or ```:=``` between keys and values, now there is no way to tell the distinction between semantic ```:assoc``` and ```:exact```. And sole key without value(which is unmatched in pair) is not allowed.

It's probably not the best choice, because the choices of syntax often cause arguments.

This PR contains map syntax support for:

1. literal and normal expression, including the map function e.g. ```(map :key :value)```
1. type and function spec
1. case statement and guard, map could be used in pattern matching now

In order to avoid ambiguity, the char % is removed from normal identifier charset, so that when keys and values are not matched in pair in a literal, e.g.,

```clojure
%{1 2 3}
```
the compiler would trigger a compile error like

```text
*error* parsing failed, expected {'at-least-one',
                                  {'character-class',"[0-9]"}}
```
rather than it parses this to a var '%' and a tuple '{1 2 3}' and causes a "reference to '%' not found" error in runtime. The error message in this situation should be much clearer to warn programmers that there is a sole key without value. But I have no clue how to improve that for this moment.

Please let me know if you have any better idea or comment.

Thanks

### CODE REVIEW

**Comment by ericbmerritt** [comment]
@hhkbp2 before I dig into this, I would ask you to clean up your commits. In general, we look for one commit per logical change. So in this case there would be one for the two reformatting commits and then one for the addition of map. I will start taking a look at the actual content as well, but figured I would give you a heads up there.

**Comment by hhkbp2** [comment]
Hi @ericbmerritt ,
Sorry for the mess of commits. I have rebased the commits and tried to tidy up a little bit.
The changes on file ```test/joxa-test-cc.jxa``` need special attention. I found it failed during compilation but I have no idea why.

**Comment by ericbmerritt** [comment]
@hhkbp2 no worries at all. Thats what PRs are for after all :) The entire test suite for joxa is less then optimal at the moment as is the way it bootstraps itself. Joxa in Joxa is a great way to validate the system but it makes for painful bootstrapping. I will start taking a look at these bits.

**Comment by ericbmerritt** [comment]
I am still tempted to go the route of `#{}` instead of `%{}`. I think there is some validity to your argument to be different from erlang (especially since the syntax is different), but I am not sure it matters that much. It sounds like you prefer the `#{}` as well but want to avoid it for collision reasons?

**Comment by hhkbp2** [comment]
@ericbmerritt To be ```#{}``` or ```%{}```, it doesn't make significantly difference. But the choice is subtle. Personally, I prefer to the way that avoids collision. I came across to some issues when I got my hands on ```let```/```let*```, which used the same keywords as Common Lisp(I didn't realize I should turn to the analogue of Clojure, since there is no ```let*``` in Clojure) but had subtly different meanings. A elaborated documentation would help in this case. 

I think there are a few rules to handles these syntax/keyword choices:

1. Follow the tradition  
        If the usage of the syntax/keyword is completely(or mostly) the same as any other programming language(or commonly used in all languages), choose it. e.g. ```fn```, ```case```, ```quote```
2. Make innovation   
    If the usage of the syntax/keyword is different, it's better to make (at least slightly?) different choice to distinguish. e.g. ```defn+```/```defn```

As long as there would not be any possible misunderstanding, it would be a good choice.

**Pull request closed without merging**
